#### The relative strength index (RSI)

A momentum indicator used in technical analysis 
that measures the magnitude of recent price changes 
to evaluate overbought or oversold conditions in 
the price of a stock or other asset.

In [2]:
import pandas_datareader as pdr
import datetime as dt

In [3]:
aapl = pdr.get_data_yahoo("AMC", dt.datetime(2020,1,1))
aapl.index = aapl.index.date
aapl.head()

                 High        Low       Open      Close       Volume  Adj Close
Date
2020-01-02  75.150002  73.797501  74.059998  75.087502  135480400.0  73.840042
2020-01-03  75.144997  74.125000  74.287498  74.357498  146322800.0  73.122154
2020-01-06  74.989998  73.187500  73.447502  74.949997  118387200.0  73.704819
2020-01-07  75.224998  74.370003  74.959999  74.597504  108872000.0  73.358185
2020-01-08  76.110001  74.290001  74.290001  75.797501  132079200.0  74.538239

#### Calculation of RSI
From wikipedia.org: https://en.wikipedia.org/wiki/Relative_strength_index

If previous price is lower than current price, then set the values.

**up = close_now – close_previous**

**down = 0**

While if the previous price is higher than current price, then set the values

**up = 0**

**down = close_previous – close_now**

Calculate the Smoothed or modified moving average (SMMA) or the exponential moving average (EMA) of down and up. To be aligned with the Yahoo! Finance, I have chosen to use the (EMA).

Calculate the relative strength (RS)

**RS = EMA(up)/EMA(down)**

Then we end with the final calculation of the Relative Strength Index (RSI).

**RSI = 100 – (100 / (1 – RSI))**

In [4]:
delta = aapl['Close'].diff()
up = delta.clip(lower=0)
down = -1*delta.clip(upper=0)

ema_up = up.ewm(com=13, adjust=False).mean()
ema_down = down.ewm(com=13, adjust=False).mean()

rs = ema_up/ema_down
aapl['RSI'] = 100 - (100/(1 + rs))
aapl.head()

,High,Low,Open,Close,Volume,Adj Close,RSI
Date,,,,,,,
2020-01-02,75.150002,73.797501,74.059998,75.087502,135480400.0,73.840042,NaN
2020-01-03,75.144997,74.125000,74.287498,74.357498,146322800.0,73.122154,0.000000
2020-01-06,74.989998,73.187500,73.447502,74.949997,118387200.0,73.704819,5.876482
2020-01-07,75.224998,74.370003,74.959999,74.597504,108872000.0,73.358185,5.663260
2020-01-08,76.110001,74.290001,74.290001,75.797501,132079200.0,74.538239,16.738942

In [5]:
import pandas as pd

In [6]:

# Create a Pandas Excel writer using XlsxWriter
excel_file = 'output.xlsx'
sheet_name = 'AAPL'
writer = pd.ExcelWriter(excel_file, engine='xlsxwriter')
aapl[14:].to_excel(writer, sheet_name=sheet_name)

# Access the XlsxWriter workbook and worksheet objects from the dataframe.
workbook = writer.book
worksheet = writer.sheets[sheet_name]
 
# Create a scatter chart object.
chart = workbook.add_chart({'type': 'line'})

# Widen the first column to display the dates.
worksheet.set_column('A:A', 12)

# Get the number of rows and column index
max_row = len(aapl)
col_y = aapl.columns.get_loc('RSI') + 1
 
# Create the chart, use a trendline to fit it
chart.add_series({
    'name':       "Apple",
    'categories': [sheet_name, 1, 0, max_row, 0],
    'values':     [sheet_name, 1, col_y, max_row, col_y],
})


# Configure axis
chart.set_x_axis({
    'name': 'Date',
    'date_axis': True,
})
chart.set_y_axis({
    'name': 'RSI',
    'major_gridlines': {'visible': False}
})
 
# Turn off the legend.
chart.set_legend({'none': True})

# Insert the chart into the worksheet in field I2
worksheet.insert_chart('I2', chart)
 
# Close and save the Excel file
writer.save()